export const HANDLE_WALLET_DATA = 'HANDLE_WALLET_DATA';
export const HANDLE_WALLET_BALANCE = 'HANDLE_WALLET_BALANCE';

export const HANDLE_MODAL_RESET = 'HANDLE_MODAL_RESET';
export const HANDLE_MODAL_DATA = 'HANDLE_MODAL_DATA';
export const HANDLE_MODAL_WALLET = 'HANDLE_MODAL_WALLET';
export const HANDLE_MODAL_QUEUETX = 'HANDLE_MODAL_QUEUETX';
export const HANDLE_MODAL_JSON = 'HANDLE_MODAL_JSON';

export const HANDLE_QUERY_TYPE = 'HANDLE_QUERY_TYPE';
export const HANDLE_QUERY_CODE = 'HANDLE_QUERY_CODE';
export const HANDLE_QUERY_CONTRACT_ADDRESS = 'HANDLE_QUERY_CONTRACT_ADDRESS';
export const HANDLE_QUERY_HEX = 'HANDLE_QUERY_HEX';
export const HANDLE_QUERY_JSON = 'HANDLE_QUERY_JSON';
export const HANDLE_QUERY_RESULT = 'HANDLE_QUERY_RESULT';

export const HANDLE_STORE_DATA = 'HANDLE_STORE_DATA';
export const HANDLE_INSTANTIATE_DATA = 'HANDLE_INSTANTIATE_DATA';
export const HANDLE_EXECUTE_DATA = 'HANDLE_EXECUTE_DATA';
export const HANDLE_MIGRATE_DATA = 'HANDLE_MIGRATE_DATA';
