export const HANDLE_WALLET_DATA = 'HANDLE_WALLET_DATA';
export const HANDLE_WALLET_BALANCE = 'HANDLE_WALLET_BALANCE';

export const HANDLE_MODAL_RESET = 'HANDLE_MODAL_RESET';
export const HANDLE_MODAL_DATA = 'HANDLE_MODAL_DATA';
export const HANDLE_MODAL_WALLET = 'HANDLE_MODAL_WALLET';
export const HANDLE_MODAL_QUEUETX = 'HANDLE_MODAL_QUEUETX';
